apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-management
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: notes-management
          image: ///
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-server
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: http-server
              path: "/health"
            initialDelaySeconds: 50
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              port: http-server
              path: "/health"
            initialDelaySeconds: 50
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2
          startupProbe:
            httpGet:
              port: http-server
              path: "/health"
            initialDelaySeconds: 50
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 2