version: '3.8'  
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: statistic-management
    working_dir: /app 
    ports:
      - "3003:3000"  # Mapeando a porta do contêiner para a porta 3002
    depends_on:
      mongo:
        condition: service_healthy  # Espera até que o serviço mongo esteja saudável

    # Healthcheck para o serviço node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"  # Mapeando a porta padrão do MongoDB
    # Healthcheck para o serviço mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
